name: "Use Reusable Workflow"

on:
  push:
    branches:
      - main  # Trigger on push to main

permissions:
  actions: write
  contents: read

jobs:
  create-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Target Repository
        uses: actions/checkout@v4

      - name: Clone Template Repository
        run: git clone https://github.com/sarthaksharma22/template-automation-repo.git

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install PyGithub

      - name: Verify File Existence
        run: ls -l template-automation-repo/scripts  # Debugging step

      - name: Run Secret Creation Script
        run: python template-automation-repo/scripts/create_secrets.py
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          GITHUB_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY: ${{ github.repository }}
