name: "Create Repository Secrets"

on:
  create:  # Runs when a new repo is created from the template
    branches:
      - main  # Default branch of the template repo

jobs:
  create-secrets:
    runs-on: ubuntu-latest
    permissions:
      actions: write  # Allow writing secrets
      contents: read  # Allow reading repo contents
      security-events: write  # Optional, for security-related secrets

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install PyGithub

      - name: Run Secret Creation Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatic GitHub Token
          GITHUB_OWNER: ${{ github.repository_owner }}
          GITHUB_REPO: ${{ github.event.repository.name }}
        run: python create_secrets.py
