name: "Create Repository Secrets"

on:
  push:
    branches:
      - main  # Run when new code is pushed to main branch

permissions:
  contents: read  # Allows reading repository content
  actions: write  # Allows modifying GitHub Actions settings

jobs:
  create-secrets:
    runs-on: ubuntu-latest
    permissions:
      secrets: write  # Required to create secrets in the repository

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install PyGithub

      - name: Run Secret Creation Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Uses GitHub Actions' built-in token
          GITHUB_OWNER: ${{ github.repository_owner }}  # Owner of the repository
          GITHUB_REPO: ${{ github.event.repository.name }}  # Name of the repository
        run: python create_secrets.py
